Fix e-mail verification returning a 500 Error
When a user goes to confirm an e-mail address, he/she is met with
an ugly 500 error:

```
NoMethodError (undefined method `accept_pending_invitations!' for #<Email:0x00007fae8df17578>):
  app/controllers/concerns/accepts_pending_invitations.rb:7:in `accept_pending_invitations'
  app/controllers/confirmations_controller.rb:16:in `after_confirmation_path_for'
```

This fixes a regression introduced by !17634.

Closes #49252