Merge branch '39181-gitlab-backgroundmigration-deserializemergerequestdiffsandcommits-error-nomethoderror-undefined-method-map-for-nil-nilclass' into 'master'
Resolve "Gitlab::BackgroundMigration::DeserializeMergeRequestDiffsAndCommits::Error: #<NoMethodError: undefined method `map' for nil:NilClass"

Closes #39181

See merge request gitlab-org/gitlab-ce!14907

(cherry picked from commit 526c47618e446bfec776b6e17462298f17fb24ee)

9245bfc2 Handle null serialised commits in background migration