[Rails5] Fix running spinach tests
1. Add support for `RAILS5=1|true` for the `bin/spinach` command.
2. Synchronize used spinach versions both for rails4 and rails5.

For rails5 it was accidently used spinach 0.10.1 instead of 0.8.10.
That brought some problems on running spinach tests.

Example of failure message:

NoMethodError: undefined method `line' for #<Spinach::Scenario:0x000000000c86ba80>
Did you mean?  lines
  /builds/gitlab-org/gitlab-ce/features/support/env.rb:52:in `before_scenario_run'