cmake is required during the installation of the rugged gem
The following error is encountered during the installation of the rugged gem:

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /usr/bin/ruby2.1 extconf.rb
    checking for cmake... no
    ERROR: CMake is required to build Rugged.
    *** extconf.rb failed ***