[Rails5] Fix `params` for DeleteUserWorker
This commit fixes the error:

```
  1) Admin::UsersController DELETE #user with projects deletes the user and their contributions when hard delete is specified
     Failure/Error: Users::DestroyService.new(current_user).execute(delete_user, options.symbolize_keys)

     NoMethodError:
       undefined method `symbolize_keys' for "{\"hard_delete\"=>\"true\"}":String
     # ./app/workers/delete_user_worker.rb:8:in `perform'
     # ./lib/gitlab/sidekiq_status/server_middleware.rb:5:in `call'
     # ./config/initializers/forbid_sidekiq_in_transactions.rb:35:in `block (2 levels) in <module:NoEnqueueingFromTransactions>'
     # ./app/models/user.rb:913:in `delete_async'
     # ./app/controllers/admin/users_controller.rb:148:in `destroy'
     # ./lib/gitlab/i18n.rb:50:in `with_locale'
     # ./lib/gitlab/i18n.rb:56:in `with_user_locale'
     # ./app/controllers/application_controller.rb:327:in `set_locale'
     # ./spec/controllers/admin/users_controller_spec.rb:28:in `block (3 levels) in <top (required)>'

Finished in 6.81 seconds (files took 13.9 seconds to load)
1 example, 1 failure
```