Merge branch '57428-actionview-template-error-undefined-method-for-nil-nilclass' into 'master'
Resolve "ActionView::Template::Error: undefined method `>' for nil:NilClass"

Closes #57428

See merge request gitlab-org/gitlab-ce!25028

(cherry picked from commit 5b23f2b016f4e5d33387d7474148d2a59b213ee6)

b177d523 Checking MR status date for related MR status tooltip
81b875f0 Added tests for merge_request_status partial
20ce370f Improved readability of issues related MR status spec