Merge branch 'update-browser-gem' into 'master'
Update browser gem to 2.2.0

A user with a certain browser would hit an Error 500:

```
ArgumentError: invalid value for Float(): "0."
  from browser/accept_language.rb:45:in `Float'
  from browser/accept_language.rb:45:in `quality'
  from browser/accept_language.rb:15:in `each'
  from browser/accept_language.rb:15:in `sort_by'
  from browser/accept_language.rb:15:in `parse'
  from browser/base.rb:13:in `initialize'
  from browser.rb:125:in `new'
  from browser.rb:125:in `block in new'
  from browser.rb:125:in `map'
  from browser.rb:125:in `new'
  from browser/action_controller.rb:15:in `browser'
  from abstract_controller/helpers.rb:67:in `browser'
  from app/views/layouts/_head.html.haml:38:in `_app_views_layouts__head_html_haml__1626593241142487258_59224880'
```

The root cause when the `Accept-Language` header would contain a float for the quality value (e.g. en-GB,en;q=0.v5).

Fixes https://github.com/fnando/browser/issues/241

Seen today via Sentry: https://sentry.gitlap.com/gitlab/gitlabcom/issues/7644/

See merge request !4811