Remove filename leading slash of -30974-issue-search-by-number.yml
The leading slash will cause some not friendly command line behavier,
for example:

vim:
```
~/gitlab-ce/changelogs/unreleased $ vim -30974-issue-search-by-number.yml
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 07 2019 15:35:43)
Unknown option argument: "-30974-issue-search-by-number.yml"
More info with: "vim -h"
```

git:
```
~/gitlab-ce/changelogs/unreleased $ git add -30974-issue-search-by-number.yml
error: unknown switch `3'
usage: git add [<options>] [--] <pathspec>...

    -n, --dry-run         dry run
    -v, --verbose         be verbose

    -i, --interactive     interactive picking
    -p, --patch           select hunks interactively
    -e, --edit            edit current diff and apply
    -f, --force           allow adding otherwise ignored files
    -u, --update          update tracked files
    -N, --intent-to-add   record only the fact that the path will be added later
    -A, --all             add changes from all tracked and untracked files
    --ignore-removal      ignore paths removed in the working tree (same as --no-all)
    --refresh             don't add, only refresh the index
    --ignore-errors       just skip files which cannot be added because of errors
    --ignore-missing      check if - even missing - files are ignored in dry run
```

There's no other unreleased changelog has a filename with leading slash,
so I think this one should be corrected.

cc !28302