Merge branch '22820-api-use-env-not-request-in-helpers' into 'master'
Resolve "NameError: undefined local variable or method `request' for #<Grape::Middleware::Error:0x007fc990..."

## What does this MR do?

Switches from `request` to `env` in an API helper method as the helpers are included in contexts lacking `request`.

## Are there points in the code the reviewer needs to double check?

I couldn't build a reproducer for this.

Closes #22820

See merge request !6615

Signed-off-by: Rémy Coutable <remy@rymai.me>