[Rails5] Fix `undefined method 'downcase'` errors in requests specs
In Rails 5.0 headers are no longer inherited from Hash.
This commit fixes errors in requests specs like:

```
1) API::V3::Builds GET /projects/:id/builds/:build_id/artifacts job with artifacts when artifacts are stored locally authorized user returns specific job artifacts
    Failure/Error: expect(response.headers).to include(download_headers)

    NoMethodError:
      undefined method `downcase' for #<Hash:0x000055e8bccc23b0>
    # ./spec/requests/api/v3/builds_spec.rb:235:in `block (6 levels) in <top (required)>'
```