[Rails5] Add `touch_later` to `Commit` model
This commit fixes errors like:

```
1) API::Todos GET /todos when unauthenticated returns authentication error
    Failure/Error: @raw.__send__(method, *args, &block) # rubocop:disable GitlabSecurity/PublicSend

    NoMethodError:
      undefined method `touch_later' for #<Gitlab::Git::Commit:0x00005573f5196270>
    # ./app/models/commit.rb:259:in `method_missing'
    # ./spec/requests/api/todos_spec.rb:12:in `block (2 levels) in <top (required)>'
```