Fix error when reloading code in Sidekiq
This commit fixes the following error in development:

    ArgumentError: A copy of Gitlab::Metrics::Transaction has been
    removed from the module tree but is still active!